spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todevelop
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      pool-name: API2CP
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        enable_lazy_load_no_trans: true
        generate_statistics: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: ${ENVIRONMENT:local}
  sql:
    init:
      platform: mysql

logging:
  level:
    liquibase: DEBUG
